<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup></PropertyGroup><ItemGroup><PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" /><ProjectReference Include="../M365Collector.Core/M365Collector.Core.csproj" /><ProjectReference Include="../M365Collector.Contracts/M365Collector.Contracts.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" /></ItemGroup></Project>
