<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup></PropertyGroup><ItemGroup><ProjectReference Include="../M365Collector.Contracts/M365Collector.Contracts.csproj" /><ProjectReference Include="../M365Collector.Security/M365Collector.Security.csproj" /><PackageReference Include="Microsoft.Identity.Client" Version="4.90.0" /><PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.90.0" /></ItemGroup></Project>
