<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWindowsForms>true</UseWindowsForms><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../M365Collector.Storage/M365Collector.Storage.csproj" /><ProjectReference Include="../M365Collector.Security/M365Collector.Security.csproj" /><ProjectReference Include="../M365Collector.Entra/M365Collector.Entra.csproj" /><ProjectReference Include="../M365Collector.Modules.TenantIdentity/M365Collector.Modules.TenantIdentity.csproj" /></ItemGroup><PropertyGroup><ApplicationIcon>../../assets/icons/application.ico</ApplicationIcon></PropertyGroup><ItemGroup><EmbeddedResource Include="../../assets/icons/*.png" LogicalName="Icons.%(Filename)%(Extension)" /><EmbeddedResource Include="../../assets/icons/application.ico" LogicalName="Icons.application.ico" /></ItemGroup></Project>
