<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWindowsForms>true</UseWindowsForms><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../M365Collector.Storage/M365Collector.Storage.csproj" /><ProjectReference Include="../M365Collector.Security/M365Collector.Security.csproj" /><ProjectReference Include="../M365Collector.Entra/M365Collector.Entra.csproj" /><ProjectReference Include="../M365Collector.Modules.TenantIdentity/M365Collector.Modules.TenantIdentity.csproj" /><ProjectReference Include="..\M365Collector.Updater\M365Collector.Updater.csproj" /></ItemGroup></Project>
